style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kohirens/tmplpress
options:
  commits:
    filters:
      Type:
        - add
        - chg
        - chr
        - dep
        - doc
        - fix
        - rfc
        - rmv
  commit_groups:
    title_maps:
      add: Added
      fix: Fixed
      chg: Changed
      chr: Chore
      dep: Deprecated
      doc: Documented
      rfc: Refactored
      rmv: Removed
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
